# Generated by Django 5.2.5 on 2025-08-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('bio', models.TextField(blank=True, verbose_name='Описание / опыт')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото')),
                ('services', models.ManyToManyField(related_name='masters', to='services_app.service', verbose_name='Оказывает услуги')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название комплекса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за комплекс')),
                ('services', models.ManyToManyField(related_name='packages', to='services_app.service', verbose_name='Услуги в комплексе')),
            ],
        ),
    ]
