# Generated by Django 5.2.5 on 2025-08-29 08:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Часы работы')),
                ('salon_name', models.CharField(max_length=100, verbose_name='Название салона')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration_min',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена от'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_app.bundle')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services_app.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='services',
            field=models.ManyToManyField(related_name='bundles', through='services_app.BundleItem', to='services_app.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services_app.servicecategory', verbose_name='Категория'),
        ),
    ]
