# Generated by Django 5.2.5 on 2025-08-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_bundle_faq_servicecategory_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'verbose_name': 'Комплекс (набор услуг)', 'verbose_name_plural': 'Комплексы (наборы услуг)'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='servicepackage',
            options={'verbose_name': 'Комплекс услуг', 'verbose_name_plural': 'Комплексы услуг'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AddField(
            model_name='service',
            name='short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
