# Generated by Django 5.2.5 on 2025-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_alter_bundle_options_alter_faq_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое название'),
        ),
    ]
