# Generated by Django 5.2.5 on 2025-09-11 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0005_alter_servicecategory_options_servicecategory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, default=60, null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_min',
            field=models.PositiveIntegerField(blank=True, default=60, null=True, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена от'),
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_min', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='services_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Вариант услуги',
                'verbose_name_plural': 'Варианты услуги',
                'ordering': ['order', 'duration_min'],
                'unique_together': {('service', 'duration_min')},
            },
        ),
    ]
