# Generated by Django 5.2.5 on 2025-09-11 08:28

from django.db import migrations

def forward(apps, schema_editor):
    Service = apps.get_model("services_app", "Service")
    ServiceOption = apps.get_model("services_app", "ServiceOption")

    for s in Service.objects.all().iterator():
        dur = s.duration_min or s.duration or 60
        price = s.price or s.price_from or 0
        if not ServiceOption.objects.filter(service_id=s.id, duration_min=dur).exists():
            ServiceOption.objects.create(
                service_id=s.id,
                duration_min=dur,
                price=price,
                is_active=s.is_active,
            )

def backward(apps, schema_editor):
    # можно оставить пустым
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0006_alter_service_duration_alter_service_duration_min_and_more'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]

