# Generated by Django 5.2.5 on 2025-09-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0007_migrate_service_to_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'ordering': ['order', 'duration_min', 'unit_type', 'units'], 'verbose_name': 'Вариант услуги', 'verbose_name_plural': 'Варианты услуги'},
        ),
        migrations.AlterUniqueTogether(
            name='serviceoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='unit_type',
            field=models.CharField(choices=[('session', 'процедуры'), ('zone', 'зоны'), ('visit', 'визиты')], default='session', max_length=16, verbose_name='Единица'),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='units',
            field=models.PositiveSmallIntegerField(default=1, help_text='Напр.: 5 процедур, 3 зоны, 2 визита', verbose_name='Кол-во единиц'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='price',
            field=models.DecimalField(decimal_places=0, help_text='Полная стоимость пакета', max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceoption',
            unique_together={('service', 'duration_min', 'unit_type', 'units')},
        ),
        migrations.AddIndex(
            model_name='serviceoption',
            index=models.Index(fields=['service', 'is_active', 'order'], name='services_ap_service_6ac5b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceoption',
            constraint=models.CheckConstraint(condition=models.Q(('duration_min__gte', 1)), name='svcopt_duration_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='serviceoption',
            constraint=models.CheckConstraint(condition=models.Q(('units__gte', 1)), name='svcopt_units_gte_1'),
        ),
    ]
