# Generated by Django 5.2.5 on 2025-09-17 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0008_alter_serviceoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Часто задаваемый вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faqs', to='services_app.servicecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='master',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='master',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='master',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Политика отмены'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Maps'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_methods',
            field=models.JSONField(blank=True, null=True, verbose_name='Методы оплаты'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='social_media',
            field=models.JSONField(blank=True, null=True, verbose_name='Социальные сети'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms_of_service',
            field=models.TextField(blank=True, null=True, verbose_name='Условия использования'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_maps_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Yandex Maps'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yclients_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YClients'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['is_active', 'order'], name='services_ap_is_acti_11c171_idx'),
        ),
    ]
