# Generated by Django 5.2.5 on 2025-09-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0009_alter_faq_options_alter_master_options_faq_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'is_popular'], name='services_ap_is_acti_d6758e_idx'),
        ),
    ]
