# Generated by Django 5.2.5 on 2025-09-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0010_service_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundleitem',
            name='gap_after_min',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='parallel_group',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
