# Generated by Django 5.2.5 on 2025-09-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0011_bundleitem_gap_after_min_bundleitem_parallel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='services',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='service',
        ),
        migrations.AddField(
            model_name='bundle',
            name='options',
            field=models.ManyToManyField(related_name='bundles', through='services_app.BundleItem', to='services_app.serviceoption'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bundle_items', to='services_app.serviceoption'),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Название варианта услуги'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Название комплекса'),
        ),
        migrations.AlterField(
            model_name='bundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services_app.bundle'),
        ),
    ]
