# Generated by Django 5.2.5 on 2025-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0012_remove_bundle_services_remove_bundleitem_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название акции')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Особенности/преимущества')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Изображение')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Скидка, %')),
                ('price_note', models.CharField(blank=True, max_length=200, verbose_name='Примечание по цене')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Начало')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('options', models.ManyToManyField(blank=True, related_name='promotions', to='services_app.serviceoption', verbose_name='Варианты услуг')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['order', '-starts_at', 'title'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='services_ap_is_acti_1a10b6_idx')],
            },
        ),
    ]
