# Generated by Django 5.2.5 on 2025-09-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0013_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['is_active', 'is_popular'], name='services_ap_is_acti_5890e8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepackage',
            index=models.Index(fields=['is_popular'], name='services_ap_is_popu_b8ca53_idx'),
        ),
    ]
