# Generated by Django 5.2.5 on 2025-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0014_bundle_is_popular_servicepackage_is_popular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='yclients_company_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID компании в YClients'),
        ),
    ]
