# Generated by Django 5.2.5 on 2025-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0015_sitesettings_yclients_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoption',
            name='yclients_service_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID услуги в YCLIENTS'),
        ),
    ]
