# Generated by Django 5.2.5 on 2025-12-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0016_serviceoption_yclients_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800x600px', null=True, upload_to='services/', verbose_name='Изображение услуги'),
        ),
    ]
