# Generated by Django 5.2.5 on 2025-12-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0017_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Рейтинг (1-5)')),
                ('date', models.DateField(verbose_name='Дата отзыва')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-date', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='services_ap_is_acti_e4e5f1_idx')],
            },
        ),
    ]
