# Generated by Django 5.2.5 on 2026-02-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0018_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Для экранов <768px. Если не загружено — используется основное изображение.', null=True, upload_to='services/mobile/', verbose_name='Изображение (мобильное)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение категории (десктоп)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='categories/mobile/', verbose_name='Изображение категории (мобильное)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Для ЧПУ-ссылок, например: ruchnye-massazhi', null=True, unique=True, verbose_name='URL-slug'),
        ),
    ]
