# Generated by Django 5.2.5 on 2026-02-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0019_service_image_mobile_servicecategory_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AddField(
            model_name='master',
            name='approach',
            field=models.TextField(blank=True, help_text='HTML разрешён', verbose_name='Подход к работе'),
        ),
        migrations.AddField(
            model_name='master',
            name='education',
            field=models.TextField(blank=True, help_text='HTML: <h2>, <ul>, <li>', verbose_name='Образование и квалификация'),
        ),
        migrations.AddField(
            model_name='master',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='master',
            name='photo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото (мобильное)'),
        ),
        migrations.AddField(
            model_name='master',
            name='reviews_text',
            field=models.TextField(blank=True, help_text='HTML разрешён', verbose_name='Отзывы и статистика'),
        ),
        migrations.AddField(
            model_name='master',
            name='work_experience',
            field=models.TextField(blank=True, help_text='HTML разрешён', verbose_name='Опыт работы'),
        ),
    ]
