# Generated by Django 5.2.5 on 2026-02-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0020_alter_master_options_master_approach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание комплекса'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/', verbose_name='Фото (мобильное)'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
