# Generated by Django 5.2.5 on 2026-02-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0021_bundle_description_bundle_image_bundle_image_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=200, verbose_name='Название комплекса')),
                ('client_name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services_app.bundle', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Заявка на комплекс',
                'verbose_name_plural': 'Заявки на комплексы',
                'ordering': ['-created_at'],
            },
        ),
    ]
