# Generated by Django 5.2.5 on 2026-02-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0022_bundlerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Категория')),
                ('service_name', models.CharField(max_length=200, verbose_name='Услуга')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на запись',
                'verbose_name_plural': 'Заявки на запись',
                'ordering': ['-created_at'],
            },
        ),
    ]
