# Generated by Django 5.2.5 on 2026-02-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0023_bookingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Промокод'),
        ),
    ]
