# Generated by Django 5.2.5 on 2026-02-17 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0024_promotion_promo_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Для <meta description>. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Если пусто — используется название услуги.', max_length=200, verbose_name='H1 заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Для тега <title>. До 60 символов. Если пусто — используется название услуги.', max_length=120, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='ЧПУ-ссылка, например: klassicheskij-massazh', max_length=200, null=True, unique=True, verbose_name='URL-slug'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Текст под H1 на странице услуги.', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.CreateModel(
            name='ServiceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текстовый блок'), ('accent', 'Акцентный блок (цветной фон)'), ('checklist', 'Чеклист (✅ пункты)'), ('identification', 'Блок идентификации (Ваш случай?)'), ('cta', 'CTA-кнопка (Записаться)'), ('price_table', 'Таблица цен'), ('accordion', 'Аккордеон (раскрывающийся блок)'), ('special_formats', 'Особые форматы'), ('subscriptions', 'Абонементы / экономия'), ('navigation', 'Навигация (Не знаете, что выбрать?)'), ('html', 'Произвольный HTML')], max_length=30, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, help_text='H2 заголовок. Можно оставить пустым.', max_length=200, verbose_name='Заголовок блока')),
                ('content', models.TextField(blank=True, help_text='HTML разрешён. Для чеклиста — каждый пункт с новой строки.', verbose_name='Содержимое')),
                ('extra', models.JSONField(blank=True, help_text='Например: {"bg_color": "#9BAE9E", "btn_text": "Записаться"}', null=True, verbose_name='Доп. настройки (JSON)')),
                ('css_class', models.CharField(blank=True, help_text='Дополнительный класс для стилизации блока.', max_length=100, verbose_name='CSS-класс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='services_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Контентный блок услуги',
                'verbose_name_plural': 'Контентные блоки услуг',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['service', 'is_active', 'order'], name='services_ap_service_f4fb39_idx')],
            },
        ),
    ]
