# Generated by Django 5.2.5 on 2026-02-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0025_alter_service_options_service_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Для <meta description>. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
    ]
