# Generated by Django 5.2.5 on 2026-02-19 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0026_alter_service_seo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_h1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='service',
            name='subtitle',
        ),
        migrations.DeleteModel(
            name='ServiceBlock',
        ),
    ]
