# Generated by Django 5.2.5 on 2026-02-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0027_alter_service_options_remove_service_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, help_text='ЧПУ-ссылка, например: klassicheskij-massazh', max_length=200, null=True, unique=True, verbose_name='URL-slug'),
        ),
    ]
