# Generated by Django 5.2.5 on 2026-02-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0029_service_order_service_seo_description_service_seo_h1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceblock',
            name='extra',
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Для акцентного/навигационного блока. Пример: #9BAE9E', max_length=20, verbose_name='Цвет фона'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='btn_sub',
            field=models.CharField(blank=True, help_text='Мелкий текст под кнопкой. Пример: Выберите удобное время — мы подтвердим запись', max_length=200, verbose_name='Подпись под кнопкой'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='btn_text',
            field=models.CharField(blank=True, help_text='Для CTA-блока. По умолчанию: Записаться онлайн', max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='heading_level',
            field=models.CharField(choices=[('h2', 'H2 — заголовок блока'), ('h3', 'H3 — подзаголовок')], default='h2', help_text='H2 — основной заголовок блока. H3 — подзаголовок внутри блока.', max_length=2, verbose_name='Уровень заголовка'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='text_color',
            field=models.CharField(blank=True, help_text='Пример: #fff или #333333', max_length=20, verbose_name='Цвет текста'),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('accent', 'Акцентный блок (цветной фон)'), ('checklist', 'Чеклист (✅ пункты)'), ('identification', 'Блок идентификации (Узнаёте себя?)'), ('cta', 'CTA-кнопка (Записаться)'), ('price_table', 'Таблица цен'), ('accordion', 'Аккордеон (раскрывающийся блок)'), ('faq', 'FAQ — вопросы и ответы'), ('special_formats', 'Особые форматы'), ('subscriptions', 'Абонементы / экономия'), ('navigation', 'Навигация (Не знаете, что выбрать?)'), ('html', 'Произвольный HTML')], max_length=30, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='content',
            field=models.TextField(blank=True, help_text='HTML разрешён. Для чеклиста/идентификации — каждый пункт с новой строки. Для FAQ — формат: Вопрос?\\nОтвет текст.\\n---\\nВопрос?\\nОтвет текст.', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок (H2 или H3). Можно оставить пустым.', max_length=200, verbose_name='Заголовок блока'),
        ),
    ]
