# Generated by Django 5.2.5 on 2026-02-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0030_remove_serviceblock_extra_serviceblock_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео (YouTube/ссылка)')], default='photo', max_length=10, verbose_name='Тип медиа')),
                ('display_mode', models.CharField(choices=[('single', 'Одиночное (полная ширина)'), ('carousel', 'В карусель (группировка)')], default='single', help_text='Одиночное — показывается как отдельная картинка. Карусель — группируется с другими фото той же группы.', max_length=10, verbose_name='Режим отображения')),
                ('carousel_group', models.CharField(blank=True, help_text='Фото с одинаковой группой объединяются в карусель. Пример: hero, cabinet, process', max_length=50, verbose_name='Группа карусели')),
                ('image', models.ImageField(blank=True, help_text='JPG/PNG/WebP. Рекомендуемый размер: 800×600px.', null=True, upload_to='services/gallery/', verbose_name='Изображение')),
                ('image_mobile', models.ImageField(blank=True, help_text='Для экранов <768px. Если пусто — используется основное.', null=True, upload_to='services/gallery/mobile/', verbose_name='Мобильная версия')),
                ('video_url', models.URLField(blank=True, help_text='YouTube или Vimeo ссылка. Пример: https://www.youtube.com/embed/XXXXX', verbose_name='URL видео')),
                ('alt_text', models.CharField(blank=True, help_text='Описание для SEO. Пример: Процесс классического массажа в студии Формула Тела', max_length=200, verbose_name='Alt-текст')),
                ('title_text', models.CharField(blank=True, help_text='Подсказка при наведении.', max_length=200, verbose_name='Title-текст')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения в правой колонке на десктопе.', verbose_name='Порядок (десктоп)')),
                ('insert_after_order', models.PositiveIntegerField(default=0, help_text="На мобильном: после какого блока показать это медиа. Используется значение поля 'Порядок' у блока. Пример: 20 — вставить после блока с порядком 20 (чеклист).", verbose_name='Вставить после блока №')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services_app.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Медиа-файл услуги',
                'verbose_name_plural': '📷 Медиа-файлы услуги',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['service', 'is_active', 'order'], name='services_ap_service_ae77e2_idx')],
            },
        ),
    ]
