# Generated by Django 5.2.5 on 2026-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0031_servicemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemedia',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4/WebM. До 50 МБ. Если заполнено — приоритет над YouTube-ссылкой.', null=True, upload_to='services/video/', verbose_name='Видеофайл'),
        ),
    ]
