# Generated by Django 5.2.5 on 2026-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0032_servicemedia_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='emoji',
            field=models.CharField(blank=True, help_text='Иконка для карточки. Пример: 💪 🔥 💧 ⚡', max_length=10, verbose_name='Эмодзи'),
        ),
        migrations.AddField(
            model_name='service',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text='Блок «Другие виды массажа». Выберите услуги для перелинковки.', to='services_app.service', verbose_name='Связанные услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, help_text='1 строка для карточки перелинковки. Пример: Восстановление после тренировок, снятие крепатуры', max_length=200, verbose_name='Краткое описание для карточки'),
        ),
    ]
