# Generated by Django 5.2.13 on 2026-04-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_app", "0034_fix_sequences"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        unique=True,
                        verbose_name="Код сертификата",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[("nominal", "На сумму"), ("service", "На услугу")],
                        default="nominal",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "nominal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=8,
                        verbose_name="Номинал (руб.)",
                    ),
                ),
                (
                    "buyer_name",
                    models.CharField(max_length=150, verbose_name="Имя покупателя"),
                ),
                (
                    "buyer_phone",
                    models.CharField(max_length=30, verbose_name="Телефон покупателя"),
                ),
                (
                    "buyer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email покупателя"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Имя получателя"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Телефон получателя"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="Пожелание на сертификате"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("delivered", "Вручён"),
                            ("redeemed", "Использован"),
                            ("expired", "Истёк"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="Действует с")),
                ("valid_until", models.DateField(verbose_name="Действует до")),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата вручения"
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата использования"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Заметка администратора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_certificates",
                        to="services_app.service",
                        verbose_name="Услуга",
                    ),
                ),
                (
                    "service_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_certificates",
                        to="services_app.serviceoption",
                        verbose_name="Вариант услуги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подарочный сертификат",
                "verbose_name_plural": "Подарочные сертификаты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificateRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=8, verbose_name="Списано (руб.)"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(max_length=200, verbose_name="Услуга"),
                ),
                (
                    "redeemed_by",
                    models.CharField(max_length=150, verbose_name="Клиент"),
                ),
                ("note", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата списания"
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="services_app.giftcertificate",
                        verbose_name="Сертификат",
                    ),
                ),
            ],
            options={
                "verbose_name": "Списание по сертификату",
                "verbose_name_plural": "Списания по сертификатам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Сертификат"),
                            ("bundle", "Комплекс"),
                            ("booking", "Запись"),
                        ],
                        max_length=20,
                        verbose_name="Тип заказа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("confirmed", "Подтверждён"),
                            ("paid", "Оплачен"),
                            ("completed", "Выполнен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=150, verbose_name="Имя клиента"),
                ),
                (
                    "client_phone",
                    models.CharField(max_length=30, verbose_name="Телефон"),
                ),
                (
                    "client_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=8, verbose_name="Сумма"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Способ оплаты"
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID платежа"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="Заметка администратора"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "order_type"],
                        name="services_ap_status_321286_idx",
                    ),
                    models.Index(
                        fields=["number"], name="services_ap_number_f377ed_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="giftcertificate",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="services_app.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddIndex(
            model_name="giftcertificate",
            index=models.Index(
                fields=["status", "is_active"], name="services_ap_status_0c3974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="giftcertificate",
            index=models.Index(fields=["code"], name="services_ap_code_85e2f6_idx"),
        ),
        migrations.AddIndex(
            model_name="giftcertificate",
            index=models.Index(
                fields=["valid_until"], name="services_ap_valid_u_c90514_idx"
            ),
        ),
    ]
