# Generated by Django 5.2.13 on 2026-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_app", "0035_giftcertificate_certificateredemption_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcertificate",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Дизайн сертификата для отправки клиенту",
                null=True,
                upload_to="certificates/",
                verbose_name="Изображение сертификата",
            ),
        ),
    ]
