# Generated by Django 5.2.5 on 2026-04-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0036_giftcertificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_emails',
            field=models.TextField(blank=True, default='', help_text='По одному email на строку (можно через запятую). Сюда падают уведомления о заявках с формы «Записаться онлайн» (wizard). Если пусто — используется ADMIN_NOTIFICATION_EMAIL из окружения.', verbose_name='Email для уведомлений о заявках'),
        ),
    ]
