# Generated by Django 5.2.13 on 2026-04-14 03:24

import services_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services_app", "0036_giftcertificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcertificate",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="JPG/PNG/WebP до 5 МБ. Дизайн сертификата для отправки клиенту.",
                null=True,
                upload_to="certificates/",
                validators=[services_app.validators.validate_image_upload],
                verbose_name="Изображение сертификата",
            ),
        ),
        migrations.AlterField(
            model_name="servicemedia",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="JPG/PNG/WebP до 5 МБ. Рекомендуемый размер: 800×600px.",
                null=True,
                upload_to="services/gallery/",
                validators=[services_app.validators.validate_image_upload],
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="servicemedia",
            name="image_mobile",
            field=models.ImageField(
                blank=True,
                help_text="JPG/PNG/WebP до 5 МБ. Для экранов <768px.",
                null=True,
                upload_to="services/gallery/mobile/",
                validators=[services_app.validators.validate_image_upload],
                verbose_name="Мобильная версия",
            ),
        ),
        migrations.AlterField(
            model_name="servicemedia",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="MP4/WebM до 50 МБ. Если заполнено — приоритет над YouTube-ссылкой.",
                null=True,
                upload_to="services/video/",
                validators=[services_app.validators.validate_video_upload],
                verbose_name="Видеофайл",
            ),
        ),
    ]
