# Generated by Django 5.2.5 on 2026-04-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0037_sitesettings_notification_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='discount',
        ),
    ]
