# Generated by Django 5.2.5 on 2026-04-15 01:04

import django.db.models.deletion
import services_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0040_alter_giftcertificate_image_alter_servicemedia_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Для <meta name=description>. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_h1',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется название комплекса.', max_length=200, verbose_name='H1 заголовок'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text="Для <title>. Если пусто — '<название> — комплекс услуг'.", max_length=120, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(blank=True, help_text='ЧПУ, например: kompleks-iz-3-massazhei', max_length=200, null=True, unique=True, verbose_name='URL-slug'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Подзаголовок под H1'),
        ),
        migrations.AddField(
            model_name='order',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services_app.bundle', verbose_name='Комплекс'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/', validators=[services_app.validators.validate_image_upload], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/', validators=[services_app.validators.validate_image_upload], verbose_name='Фото (мобильное)'),
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['slug'], name='services_ap_slug_c3d104_idx'),
        ),
    ]
