# Generated by Django 5.2.5 on 2026-04-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0043_populate_category_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Расчётный счёт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_bik',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='БИК банка'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_corr_account',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='inn',
            field=models.CharField(blank=True, default='', help_text='10 цифр (ООО) или 12 цифр (ИП)', max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_address',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Например: ИП Иванов Иван Иванович или ООО «Название»', max_length=200, verbose_name='Полное юр. наименование'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ogrn',
            field=models.CharField(blank=True, default='', help_text='13 цифр (ООО) или 15 цифр (ИП)', max_length=15, verbose_name='ОГРН / ОГРНИП'),
        ),
    ]
