# Generated by Django 5.2.5 on 2026-04-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0045_populate_organization_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='slug',
            field=models.SlugField(blank=True, help_text='ЧПУ для /masters/<slug>/. Автозаполняется из ФИО.', max_length=100, null=True, unique=True, verbose_name='URL-slug'),
        ),
        migrations.AddIndex(
            model_name='master',
            index=models.Index(fields=['slug'], name='services_ap_slug_e7c705_idx'),
        ),
    ]
