# Generated by Django 5.2.5 on 2026-04-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0047_populate_master_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Для <meta description>. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_h1',
            field=models.CharField(blank=True, default='', help_text='Если пусто — используется название категории.', max_length=200, verbose_name='H1 заголовок'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Для <title>. Без суффикса «| Формула Тела» — шаблон добавит сам.', max_length=120, verbose_name='SEO Title'),
        ),
    ]
