# Generated by Django 5.2.5 on 2026-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0048_servicecategory_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлён'),
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создана'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлена'),
        ),
    ]
