# Generated by Django 5.2.5 on 2026-04-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0049_bundle_created_at_bundle_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает оплаты'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён')], default='not_required', max_length=25, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, default='', help_text='confirmation_url от YooKassa', verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время визита'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services_app.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services_app.serviceoption', verbose_name='Вариант услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID мастера (YClients)'),
        ),
        migrations.AddField(
            model_name='order',
            name='yclients_record_hash',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='YClients record hash'),
        ),
        migrations.AddField(
            model_name='order',
            name='yclients_record_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='YClients record id'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=False, help_text='Пока выключено — на сайте при записи на услугу клиент видит только офлайн-способы (наличные/картой в салоне). Включать после модерации YooKassa и прописанных YOOKASSA_SHOP_ID / YOOKASSA_SECRET_KEY в .env.', verbose_name='Онлайн-оплата через YooKassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('certificate', 'Сертификат'), ('bundle', 'Комплекс'), ('booking', 'Запись'), ('service', 'Услуга')], max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, help_text='YooKassa payment id (uuid)', max_length=100, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('cash', 'Наличными в салоне'), ('card_offline', 'Картой в салоне')], default='', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='services_ap_payment_d3f4b1_idx'),
        ),
    ]
