# Generated by Django 5.2.5 on 2026-04-19 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0050_order_service_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='certificate_theme',
            field=models.CharField(choices=[('dark', 'Тёмная (синяя)'), ('pink', 'Розовая')], default='pink', max_length=10, verbose_name='Тема сертификата'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='is_certificate',
            field=models.BooleanField(default=False, help_text='Показывать на странице /certificates/ как подарочный сертификат.', verbose_name='Доступен как сертификат'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_certificates', to='services_app.bundle', verbose_name='Комплекс'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('nominal', 'На сумму'), ('service', 'На услугу'), ('bundle', 'Комплекс')], default='nominal', max_length=10, verbose_name='Тип'),
        ),
    ]
