# Generated by Django 5.2.5 on 2026-04-20 07:34

from django.db import migrations, models


def rename_dark_to_graphite(apps, schema_editor):
    Bundle = apps.get_model("services_app", "Bundle")
    Bundle.objects.filter(certificate_theme="dark").update(certificate_theme="graphite")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0051_certificate_bundle_and_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcertificate',
            name='theme',
            field=models.CharField(choices=[('pink', 'Для неё'), ('graphite', 'Для него'), ('spring', '8 марта'), ('military', '23 февраля'), ('birthday', 'День рождения'), ('winter', 'Новый год'), ('valentine', '14 февраля'), ('spa', 'SPA релакс')], default='pink', max_length=16, verbose_name='Оформление'),
        ),
        migrations.RunPython(rename_dark_to_graphite, noop),
        migrations.AlterField(
            model_name='bundle',
            name='certificate_theme',
            field=models.CharField(choices=[('pink', 'Для неё'), ('graphite', 'Для него'), ('spring', '8 марта'), ('military', '23 февраля'), ('birthday', 'День рождения'), ('winter', 'Новый год'), ('valentine', '14 февраля'), ('spa', 'SPA релакс')], default='pink', max_length=16, verbose_name='Тема сертификата'),
        ),
    ]
