# Generated by Django 5.2.5 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0052_cert_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='master_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Предпочитаемый мастер'),
        ),
    ]
