# Generated by Django 5.2.5 on 2026-04-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0053_add_master_name_to_booking_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_manager_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на прямой чат с менеджером, например https://t.me/manager_username', verbose_name='Личный контакт менеджера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_max',
            field=models.URLField(blank=True, default='', help_text='Например: https://max.ru/formulatela', verbose_name='MAX'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_telegram',
            field=models.URLField(blank=True, default='', help_text='Например: https://t.me/formulatela58', verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_vk',
            field=models.URLField(blank=True, default='', help_text='Например: https://vk.me/formulatela', verbose_name='VK-сообщения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_whatsapp',
            field=models.URLField(blank=True, default='', help_text='Например: https://wa.me/78412393433', verbose_name='WhatsApp'),
        ),
    ]
