# Generated by Django 5.2.5 on 2026-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0054_sitesettings_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть категорию со всех страниц сайта (главная, /services/, sitemap). Услуги внутри остаются активными, но не отображаются в каталоге.', verbose_name='Активна'),
        ),
    ]
