# Generated by Django 5.2.5 on 2026-04-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0055_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Для meta description. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Для тега title. Если пусто — «название — комплекс услуг».', max_length=120, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='master',
            name='education',
            field=models.TextField(blank=True, help_text='Разрешён HTML: заголовки h2, списки ul/li', verbose_name='Образование и квалификация'),
        ),
        migrations.AlterField(
            model_name='master',
            name='slug',
            field=models.SlugField(blank=True, help_text='ЧПУ для /masters/[slug]/. Автозаполняется из ФИО.', max_length=100, null=True, unique=True, verbose_name='URL-slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Для meta description. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть категорию со всех страниц сайта (главная, services, sitemap). Услуги внутри остаются активными, но не отображаются в каталоге.', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_description',
            field=models.CharField(blank=True, default='', help_text='Для meta description. До 160 символов.', max_length=300, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='seo_title',
            field=models.CharField(blank=True, default='', help_text='Для title. Без суффикса «| Формула Тела» — шаблон добавит сам.', max_length=120, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Фотография'), ('video', 'Видео (YouTube-ссылка)')], default='photo', max_length=10, verbose_name='Тип медиа'),
        ),
    ]
