# Generated by Django 5.2.13 on 2026-04-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0056_alter_bundle_seo_description_alter_bundle_seo_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID в MAX')),
                ('display_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя из MAX')),
                ('client_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Имя как назвался боту')),
                ('client_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='Первый визит')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
                ('context', models.JSONField(blank=True, default=dict, help_text='JSON: {"services_viewed": [slug], "faqs_viewed": [id], "bookings_count": N}', verbose_name='Контекст')),
            ],
            options={
                'verbose_name': 'Пользователь MAX-бота',
                'verbose_name_plural': 'Пользователи MAX-бота',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Статья помощи (бот)',
                'verbose_name_plural': 'Статьи помощи (бот)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='source',
            field=models.CharField(choices=[('wizard', 'Форма-мастер'), ('bot_max', 'MAX-бот'), ('other', 'Другое')], default='wizard', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='bot_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='services_app.botuser', verbose_name='Пользователь бота'),
        ),
    ]
