# Generated by Django 5.2.5 on 2026-04-25 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0057_botuser_helparticle_bookingrequest_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(help_text='Куда отправить ответ менеджера. У одного BotUser может быть несколько чатов.', verbose_name='ID чата в MAX')),
                ('question', models.TextField(verbose_name='Вопрос клиента')),
                ('asked_at', models.DateTimeField(auto_now_add=True, verbose_name='Задан')),
                ('reply_text', models.TextField(blank=True, default='', help_text='Заполните чтобы action «Отправить» стал доступен.', verbose_name='Ответ менеджера')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Отвечен')),
                ('sent_to_max', models.BooleanField(default=False, help_text='True после успешного bot.send_message клиенту.', verbose_name='Доставлен в MAX')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='services_app.botuser', verbose_name='Пользователь бота')),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_inquiries_replied', to=settings.AUTH_USER_MODEL, verbose_name='Кто ответил')),
            ],
            options={
                'verbose_name': 'Вопрос клиента (бот)',
                'verbose_name_plural': 'Вопросы клиентов (бот)',
                'ordering': ['-asked_at'],
            },
        ),
    ]
