# Generated by Django 5.2.5 on 2026-04-27 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0058_botinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='yclients_staff_id',
            field=models.CharField(blank=True, db_index=True, help_text='Маппинг для AI-помощника на нативную запись через YClients API. Возьмите ID из YClients (Настройки → Сотрудники).', max_length=20, null=True, verbose_name='ID сотрудника в YClients'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='False когда диалог закрыт (новый /start, явный cancel, автоматический cleanup через 7+ дней без активности).', verbose_name='Активный')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='services_app.botuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Диалог AI (бот)',
                'verbose_name_plural': 'Диалоги AI (бот)',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], max_length=16, verbose_name='Роль')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое')),
                ('action_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Тип action')),
                ('action_data', models.JSONField(blank=True, null=True, verbose_name='Данные action')),
                ('tool_call', models.JSONField(blank=True, null=True, verbose_name='Tool call (raw)')),
                ('tool_call_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID tool_call')),
                ('tokens_in', models.IntegerField(default=0, verbose_name='Токены вход')),
                ('tokens_out', models.IntegerField(default=0, verbose_name='Токены выход')),
                ('latency_ms', models.IntegerField(blank=True, null=True, verbose_name='Latency, мс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='services_app.conversation', verbose_name='Диалог')),
            ],
            options={
                'verbose_name': 'Сообщение AI (бот)',
                'verbose_name_plural': 'Сообщения AI (бот)',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['bot_user', '-last_message_at'], name='services_ap_bot_use_24569f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['is_active', '-last_message_at'], name='services_ap_is_acti_8b6f15_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='services_ap_convers_de121f_idx'),
        ),
    ]
