# Generated by Django 5.2.5 on 2026-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0059_master_yclients_staff_id_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='outcome',
            field=models.CharField(blank=True, choices=[('success', 'Закрыта записью'), ('abandoned', 'Клиент ушёл / отменил'), ('redirected', 'Передан менеджеру'), ('error', 'Технический сбой')], db_index=True, default='', help_text='Заполняется при закрытии conversation. Пустое — диалог активен.', max_length=16, verbose_name='Результат'),
        ),
    ]
