# Generated by Django 5.2.5 on 2026-04-29 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0060_conversation_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="Для проактивных сообщений (напоминания о записях). Обновляется на каждом event'е от пользователя.", null=True, verbose_name='Chat ID в MAX'),
        ),
        migrations.CreateModel(
            name='BookingReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yclients_record_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='YClients record ID')),
                ('chat_id', models.BigIntegerField(help_text='Snapshot — chat_id может протухнуть в BotUser', verbose_name='Chat ID (snapshot)')),
                ('visit_at', models.DateTimeField(verbose_name='Время визита')),
                ('kind', models.CharField(choices=[('day_before', 'За день (T-24h)'), ('two_hours', 'За 2 часа (T-2h)')], max_length=16, verbose_name='Вид')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent_no_reply', 'Отправлено, без ответа'), ('sent', 'Отправлено (T-2h без кнопок)'), ('confirmed', 'Клиент подтвердил'), ('reschedule', 'Клиент просит перенести'), ('cancelled', 'Клиент отменил'), ('escalated', 'Менеджер уведомлён'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(verbose_name='Запланировано на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Ответ клиента')),
                ('master_name', models.CharField(blank=True, max_length=120, verbose_name='Мастер')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='Услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='services_app.bookingrequest', verbose_name='Заявка')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='services_app.botuser', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Напоминание о записи',
                'verbose_name_plural': 'Напоминания о записях',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='services_ap_status_d43ce3_idx'), models.Index(fields=['kind', 'visit_at'], name='services_ap_kind_fe6412_idx')],
                'unique_together': {('yclients_record_id', 'kind')},
            },
        ),
    ]
