# Generated by Django 5.2.5 on 2026-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0061_booking_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text='Список тегов из SERVICE_GOAL_CHOICES. Используется AI-ботом для подбора услуг под запрос клиента. Пример: ["relax", "antistress"] — для расслабляющих услуг.', verbose_name='Цели / результаты'),
        ),
    ]
