# Generated by Django 5.2.5 on 2026-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0062_service_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contraindications',
            field=models.TextField(blank=True, default='', help_text='Текст противопоказаний — показывается клиенту в карточке услуги перед записью. Пример: «беременность, повышенное давление, недавние операции».', verbose_name='Противопоказания'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_health_check',
            field=models.BooleanField(default=False, help_text='Если True — AI-бот спросит клиента о беременности / давлении / операциях ПЕРЕД записью. При наличии противопоказания запись переадресуется менеджеру.', verbose_name='Требует проверки здоровья'),
        ),
    ]
