# Generated by Django 5.2.5 on 2026-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0063_service_health_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='source',
            field=models.CharField(choices=[('wizard', 'Форма-мастер'), ('bot_max', 'MAX-бот'), ('yclients_admin', 'YClients админка'), ('other', 'Другое')], default='wizard', max_length=20, verbose_name='Источник'),
        ),
    ]
