# Generated by Django 5.2.5 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0067_fewshotexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='health_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Кэш health-флагов из Ayla profile для system prompt: pregnant, breastfeeding, diabetes_t1/t2, prediabetes, hypertension, gi_problems, thyroid, menopause, eating_disorder, meds, allergies (list), allergies_vague, *_skipped. Sync при upsert профиля в Ayla.', verbose_name='Health flags (cache)'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='nutrition_onboarded_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp когда пользователь успешно завершил анкету (complete=true).', null=True, verbose_name='Nutrition анкета пройдена'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='nutrition_settings',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"daily_report_time": "21:00", "daily_report_enabled": true, "water_reminders_enabled": false, "evening_inline_shown_at": "...", "food_disclaimer_shown_at": "...", "alcohol_hint_shown_at": "...", "daily_report": {date, content, generated_at} cache}', verbose_name='Nutrition UI settings'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='timezone',
            field=models.CharField(blank=True, default='Europe/Moscow', help_text='IANA timezone для quiet hours и push-времени дневного отчёта.', max_length=64, verbose_name='Timezone (IANA)'),
        ),
    ]
