# Generated by Django 5.2.5 on 2026-05-05 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0068_botuser_nutrition_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название')),
                ('detector_function', models.CharField(help_text='Полное имя async-функции, e.g. maxbot.nudges.detectors.evening_sweets', max_length=200, verbose_name='FQN детектора')),
                ('min_repeats', models.IntegerField(default=1, verbose_name='Мин. повторов')),
                ('min_active_days', models.IntegerField(default=1, verbose_name='Мин. дней с активностью')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10, verbose_name='Severity')),
                ('advice_template', models.TextField(blank=True, verbose_name='Шаблон совета')),
                ('requires_health_flags_absent', models.JSONField(blank=True, default=list, help_text='Список slug-ов: ["eating_disorder", "pregnant"]', verbose_name='Health-флаги, при которых пропускать')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Pattern rule',
                'verbose_name_plural': 'Pattern rules',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='NudgeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(db_index=True, max_length=50, verbose_name='Тип')),
                ('nudge_class', models.CharField(max_length=20, verbose_name='Класс')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Обнаружен')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован')),
                ('blocked_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина блока')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Просмотрен')),
                ('clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Кликнут')),
                ('clicked_button', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кнопка')),
                ('ignored_at', models.DateTimeField(blank=True, null=True, verbose_name='Проигнорирован')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_events', to='services_app.botuser', verbose_name='Пользователь')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nudge_event', to='services_app.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Нудж — событие',
                'verbose_name_plural': 'Нуджи — события',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['bot_user', 'kind', '-detected_at'], name='services_ap_bot_use_2b95fe_idx'), models.Index(fields=['bot_user', 'nudge_class', '-sent_at'], name='services_ap_bot_use_94f936_idx')],
            },
        ),
        migrations.CreateModel(
            name='NudgeMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Тип нуджа')),
                ('nudge_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='Класс нуджа')),
                ('mode', models.CharField(choices=[('off', 'Не показывать'), ('less_often', 'Реже')], default='off', max_length=20, verbose_name='Режим')),
                ('reason', models.CharField(choices=[('user_explicit_off', 'Кнопка «Не показывай»'), ('user_explicit_less', 'Кнопка «Реже»'), ('user_settings', 'Из настроек'), ('auto_ignored_twice', 'Дважды проигнорирован')], max_length=30, verbose_name='Причина')),
                ('expires_at', models.DateTimeField(blank=True, help_text='NULL = forever', null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudge_mutes', to='services_app.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Нудж — заглушка',
                'verbose_name_plural': 'Нуджи — заглушки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot_user', 'kind'], name='services_ap_bot_use_4db9d5_idx'), models.Index(fields=['bot_user', 'nudge_class'], name='services_ap_bot_use_7dc8da_idx')],
            },
        ),
    ]
