"""
Тесты для Order + GiftCertificate + API сертификатов.
"""
import json
from datetime import date, timedelta
from decimal import Decimal

import pytest
from model_bakery import baker


# ── Модели ──────────────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestOrderModel:
    def test_order_number_autogenerated(self):
        order = baker.make(
            "services_app.Order",
            order_type="certificate",
            client_name="Тест",
            client_phone="+70001112233",
        )
        assert order.number.startswith("FT-")
        assert len(order.number) == 16  # FT-YYYYMMDD-XXXX

    def test_order_number_unique(self):
        o1 = baker.make("services_app.Order", order_type="certificate",
                        client_name="A", client_phone="1")
        o2 = baker.make("services_app.Order", order_type="certificate",
                        client_name="B", client_phone="2")
        assert o1.number != o2.number

    def test_order_str(self, order):
        assert "FT-" in str(order)
        assert "Сертификат" in str(order)


@pytest.mark.django_db
class TestGiftCertificateModel:
    def test_code_autogenerated(self, gift_certificate):
        assert gift_certificate.code.startswith("FT-")
        assert len(gift_certificate.code) == 12  # FT-XXXX-XXXX

    def test_is_valid_paid(self, gift_certificate):
        assert gift_certificate.is_valid is True

    def test_is_valid_pending(self, gift_certificate):
        gift_certificate.status = "pending"
        assert gift_certificate.is_valid is False

    def test_is_valid_expired_date(self, gift_certificate):
        gift_certificate.valid_until = date.today() - timedelta(days=1)
        assert gift_certificate.is_valid is False

    def test_remaining_value_full(self, gift_certificate):
        assert gift_certificate.remaining_value == Decimal("3000")

    def test_remaining_value_after_redemption(self, gift_certificate):
        baker.make(
            "services_app.CertificateRedemption",
            certificate=gift_certificate,
            amount=Decimal("1500"),
            service_name="Массаж",
            redeemed_by="Клиент",
        )
        assert gift_certificate.remaining_value == Decimal("1500")

    def test_remaining_value_service_type(self, gift_certificate):
        gift_certificate.certificate_type = "service"
        assert gift_certificate.remaining_value is None

    def test_str(self, gift_certificate):
        s = str(gift_certificate)
        assert "FT-" in s
        assert "3000" in s


# ── API ─────────────────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestCertificateRequestAPI:
    url = "/api/certificates/request/"

    def test_success_nominal(self, client, mock_telegram):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_name": "Тестов Тест",
            "buyer_phone": "+79990001122",
            "recipient_name": "Получатель",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert "order_number" in data

        from services_app.models import Order, GiftCertificate
        order = Order.objects.get(number=data["order_number"])
        assert order.order_type == "certificate"
        assert order.total_amount == 3000

        cert = GiftCertificate.objects.get(order=order)
        assert cert.certificate_type == "nominal"
        assert cert.nominal == 3000
        assert cert.buyer_name == "Тестов Тест"
        assert cert.recipient_name == "Получатель"
        assert cert.status == "pending"
        assert cert.code.startswith("FT-")

    def test_success_service(self, client, service, mock_telegram):
        payload = {
            "certificate_type": "service",
            "service_id": service.id,
            "buyer_name": "Тестов",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True

    def test_missing_buyer_name(self, client):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_missing_buyer_phone(self, client):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_name": "Тест",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_invalid_type(self, client):
        payload = {
            "certificate_type": "unknown",
            "buyer_name": "Тест",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_nominal_zero(self, client):
        payload = {
            "certificate_type": "nominal",
            "nominal": 0,
            "buyer_name": "Тест",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_service_not_found(self, client):
        payload = {
            "certificate_type": "service",
            "service_id": 99999,
            "buyer_name": "Тест",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 404

    def test_telegram_called(self, client, mock_telegram, settings):
        settings.TELEGRAM_BOT_TOKEN = "test-token"
        settings.TELEGRAM_CHAT_ID = "12345"
        payload = {
            "certificate_type": "nominal",
            "nominal": 5000,
            "buyer_name": "Тестов",
            "buyer_phone": "+79990001122",
        }
        client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert mock_telegram.called


@pytest.mark.django_db
class TestCertificateCheckAPI:
    url = "/api/certificates/check/"

    def test_valid_certificate(self, client, gift_certificate):
        resp = client.get(f"{self.url}?code={gift_certificate.code}")
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert data["certificate"]["code"] == gift_certificate.code
        assert data["certificate"]["valid"] is True
        assert data["certificate"]["remaining_value"] == "3000"

    def test_not_found(self, client):
        resp = client.get(f"{self.url}?code=INVALID-CODE")
        assert resp.status_code == 404
        assert resp.json()["success"] is False

    def test_empty_code(self, client):
        resp = client.get(self.url)
        assert resp.status_code == 400


# ── Страница ────────────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestCertificatesPage:
    def test_status_200(self, client):
        resp = client.get("/certificates/")
        assert resp.status_code == 200

    def test_template(self, client):
        resp = client.get("/certificates/")
        assert "website/certificates.html" in [t.name for t in resp.templates]


# ── Онлайн-оплата сертификатов ───────────────────────────────────────────────


@pytest.mark.django_db
class TestCertificateOnlinePayment:
    url = "/api/certificates/request/"

    @pytest.fixture
    def online_enabled(self, db):
        from model_bakery import baker
        from services_app.models import SiteSettings
        SiteSettings.objects.all().delete()
        return baker.make(SiteSettings, online_payment_enabled=True)

    @pytest.fixture
    def mock_payment_service(self, monkeypatch):
        from unittest.mock import MagicMock
        svc = MagicMock()
        svc.create_for_order.return_value = "https://yookassa.test/confirm/cert1"
        monkeypatch.setattr("payments.services.PaymentService", MagicMock(return_value=svc))
        return svc

    def _payload(self, **kwargs):
        base = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_name": "Андрей",
            "buyer_phone": "+79990001122",
            "payment_method": "online",
        }
        base.update(kwargs)
        return base

    def test_online_returns_payment_url(self, client, online_enabled, mock_payment_service):
        resp = client.post(
            self.url, json.dumps(self._payload()),
            content_type="application/json",
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert data["payment_method"] == "online"
        assert data["payment_url"] == "https://yookassa.test/confirm/cert1"
        assert "order_number" in data

    def test_online_creates_order_with_pending_status(self, client, online_enabled, mock_payment_service):
        resp = client.post(
            self.url, json.dumps(self._payload()),
            content_type="application/json",
        )
        from services_app.models import Order
        order = Order.objects.get(number=resp.json()["order_number"])
        assert order.payment_method == "online"
        assert order.payment_status == "pending"

    def test_online_disabled_returns_error(self, client, db):
        from model_bakery import baker
        from services_app.models import SiteSettings
        SiteSettings.objects.all().delete()
        baker.make(SiteSettings, online_payment_enabled=False)
        resp = client.post(
            self.url, json.dumps(self._payload()),
            content_type="application/json",
        )
        assert resp.status_code == 400
        assert resp.json()["error"] == "online_payment_disabled"

    def test_cash_flow_unchanged(self, client, mock_telegram):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_name": "Андрей",
            "buyer_phone": "+79990001122",
            "payment_method": "cash",
        }
        resp = client.post(
            self.url, json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert "payment_url" not in data


# ── fulfill_paid_certificate ─────────────────────────────────────────────────


@pytest.mark.django_db
class TestFulfillPaidCertificate:
    @pytest.fixture
    def pending_cert_order(self, db, service):
        from decimal import Decimal
        from datetime import date, timedelta
        from services_app.models import Order, GiftCertificate
        order = Order.objects.create(
            order_type="certificate",
            payment_method="online",
            payment_status="succeeded",
            client_name="Андрей",
            client_phone="+79990001122",
            client_email="test@example.com",
            total_amount=Decimal("3000"),
        )
        today = date.today()
        GiftCertificate.objects.create(
            order=order,
            certificate_type="nominal",
            nominal=Decimal("3000"),
            buyer_name="Андрей",
            buyer_phone="+79990001122",
            buyer_email="test@example.com",
            valid_from=today,
            valid_until=today + timedelta(days=180),
            status="pending",
            is_active=False,
        )
        return order

    def test_sets_cert_status_paid(self, pending_cert_order, mock_telegram):
        from payments.tasks import fulfill_paid_certificate
        from services_app.models import GiftCertificate
        fulfill_paid_certificate(pending_cert_order.pk)
        cert = GiftCertificate.objects.get(order=pending_cert_order)
        assert cert.status == "paid"
        assert cert.is_active is True
        assert cert.paid_at is not None

    def test_idempotent(self, pending_cert_order, mock_telegram):
        from payments.tasks import fulfill_paid_certificate
        from services_app.models import GiftCertificate
        cert = GiftCertificate.objects.get(order=pending_cert_order)
        cert.status = "paid"
        cert.save(update_fields=["status"])
        fulfill_paid_certificate(pending_cert_order.pk)
        # Вызов второй раз — статус не сброшен
        cert.refresh_from_db()
        assert cert.status == "paid"

    def test_sends_telegram(self, pending_cert_order, monkeypatch):
        from unittest.mock import MagicMock
        mock_tg = MagicMock()
        monkeypatch.setattr("payments.tasks.send_notification_telegram", mock_tg)
        from payments.tasks import fulfill_paid_certificate
        fulfill_paid_certificate(pending_cert_order.pk)
        assert mock_tg.called
        call_text = mock_tg.call_args[0][0]
        assert "Сертификат оплачен" in call_text

    def test_sends_email_to_buyer(self, pending_cert_order, mock_telegram, monkeypatch):
        from unittest.mock import MagicMock
        mock_email = MagicMock(return_value=True)
        monkeypatch.setattr("payments.tasks.send_certificate_email", mock_email)
        from payments.tasks import fulfill_paid_certificate
        fulfill_paid_certificate(pending_cert_order.pk)
        mock_email.assert_called_once()


# ── Webhook routing для сертификатов ────────────────────────────────────────


@pytest.mark.django_db
class TestWebhookRoutesCertificate:
    @pytest.fixture(autouse=True)
    def disable_ip_check(self, settings):
        settings.YOOKASSA_WEBHOOK_STRICT_IP = False

    def test_routes_certificate_to_fulfill_paid_certificate(
        self, client, monkeypatch, mock_telegram, django_capture_on_commit_callbacks,
    ):
        from decimal import Decimal
        from datetime import date, timedelta
        from unittest.mock import MagicMock
        from services_app.models import Order, GiftCertificate

        order = Order.objects.create(
            order_type="certificate",
            payment_method="online",
            payment_status="pending",
            payment_id="cert_pay_1",
            client_name="A",
            client_phone="+70001",
            total_amount=Decimal("1000"),
        )
        today = date.today()
        GiftCertificate.objects.create(
            order=order, certificate_type="nominal", nominal=Decimal("1000"),
            buyer_name="A", buyer_phone="+70001",
            valid_from=today, valid_until=today + timedelta(days=180),
            status="pending",
        )

        mock_verify = MagicMock(return_value={"status": "succeeded", "id": "cert_pay_1"})
        monkeypatch.setattr("payments.views.get_yookassa_client",
                            MagicMock(return_value=MagicMock(find_payment=mock_verify)))
        mock_cert_task = MagicMock()
        mock_bundle_task = MagicMock()
        mock_order_task = MagicMock()
        monkeypatch.setattr("payments.views.fulfill_paid_certificate", mock_cert_task)
        monkeypatch.setattr("payments.views.fulfill_paid_bundle", mock_bundle_task)
        monkeypatch.setattr("payments.views.fulfill_paid_order", mock_order_task)

        payload = {"type": "notification", "event": "payment.succeeded",
                   "object": {"id": "cert_pay_1", "status": "succeeded"}}
        # Wrap в capture-контекст: enqueue идёт через transaction.on_commit,
        # под pytest.mark.django_db реальный commit не происходит — execute=True
        # прогоняет callback'и при выходе из with, до assertion'ов.
        with django_capture_on_commit_callbacks(execute=True):
            client.post("/api/payments/yookassa/webhook/",
                        json.dumps(payload), content_type="application/json")

        mock_cert_task.delay.assert_called_once_with(order.id)
        mock_bundle_task.delay.assert_not_called()
        mock_order_task.delay.assert_not_called()
