"""
Тесты для Order + GiftCertificate + API сертификатов.
"""
import json
from datetime import date, timedelta
from decimal import Decimal

import pytest
from model_bakery import baker


# ── Модели ──────────────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestOrderModel:
    def test_order_number_autogenerated(self):
        order = baker.make(
            "services_app.Order",
            order_type="certificate",
            client_name="Тест",
            client_phone="+70001112233",
        )
        assert order.number.startswith("FT-")
        assert len(order.number) == 16  # FT-YYYYMMDD-XXXX

    def test_order_number_unique(self):
        o1 = baker.make("services_app.Order", order_type="certificate",
                        client_name="A", client_phone="1")
        o2 = baker.make("services_app.Order", order_type="certificate",
                        client_name="B", client_phone="2")
        assert o1.number != o2.number

    def test_order_str(self, order):
        assert "FT-" in str(order)
        assert "Сертификат" in str(order)


@pytest.mark.django_db
class TestGiftCertificateModel:
    def test_code_autogenerated(self, gift_certificate):
        assert gift_certificate.code.startswith("FT-")
        assert len(gift_certificate.code) == 12  # FT-XXXX-XXXX

    def test_is_valid_paid(self, gift_certificate):
        assert gift_certificate.is_valid is True

    def test_is_valid_pending(self, gift_certificate):
        gift_certificate.status = "pending"
        assert gift_certificate.is_valid is False

    def test_is_valid_expired_date(self, gift_certificate):
        gift_certificate.valid_until = date.today() - timedelta(days=1)
        assert gift_certificate.is_valid is False

    def test_remaining_value_full(self, gift_certificate):
        assert gift_certificate.remaining_value == Decimal("3000")

    def test_remaining_value_after_redemption(self, gift_certificate):
        baker.make(
            "services_app.CertificateRedemption",
            certificate=gift_certificate,
            amount=Decimal("1500"),
            service_name="Массаж",
            redeemed_by="Клиент",
        )
        assert gift_certificate.remaining_value == Decimal("1500")

    def test_remaining_value_service_type(self, gift_certificate):
        gift_certificate.certificate_type = "service"
        assert gift_certificate.remaining_value is None

    def test_str(self, gift_certificate):
        s = str(gift_certificate)
        assert "FT-" in s
        assert "3000" in s


# ── API ─────────────────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestCertificateRequestAPI:
    url = "/api/certificates/request/"

    def test_success_nominal(self, client, mock_telegram):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_name": "Тестов Тест",
            "buyer_phone": "+79990001122",
            "recipient_name": "Получатель",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert "order_number" in data

        from services_app.models import Order, GiftCertificate
        order = Order.objects.get(number=data["order_number"])
        assert order.order_type == "certificate"
        assert order.total_amount == 3000

        cert = GiftCertificate.objects.get(order=order)
        assert cert.certificate_type == "nominal"
        assert cert.nominal == 3000
        assert cert.buyer_name == "Тестов Тест"
        assert cert.recipient_name == "Получатель"
        assert cert.status == "pending"
        assert cert.code.startswith("FT-")

    def test_success_service(self, client, service, mock_telegram):
        payload = {
            "certificate_type": "service",
            "service_id": service.id,
            "buyer_name": "Тестов",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True

    def test_missing_buyer_name(self, client):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_missing_buyer_phone(self, client):
        payload = {
            "certificate_type": "nominal",
            "nominal": 3000,
            "buyer_name": "Тест",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_invalid_type(self, client):
        payload = {
            "certificate_type": "unknown",
            "buyer_name": "Тест",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_nominal_zero(self, client):
        payload = {
            "certificate_type": "nominal",
            "nominal": 0,
            "buyer_name": "Тест",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 400

    def test_service_not_found(self, client):
        payload = {
            "certificate_type": "service",
            "service_id": 99999,
            "buyer_name": "Тест",
            "buyer_phone": "+79990001122",
        }
        resp = client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert resp.status_code == 404

    def test_telegram_called(self, client, mock_telegram, settings):
        settings.TELEGRAM_BOT_TOKEN = "test-token"
        settings.TELEGRAM_CHAT_ID = "12345"
        payload = {
            "certificate_type": "nominal",
            "nominal": 5000,
            "buyer_name": "Тестов",
            "buyer_phone": "+79990001122",
        }
        client.post(
            self.url,
            json.dumps(payload),
            content_type="application/json",
        )
        assert mock_telegram.called


@pytest.mark.django_db
class TestCertificateCheckAPI:
    url = "/api/certificates/check/"

    def test_valid_certificate(self, client, gift_certificate):
        resp = client.get(f"{self.url}?code={gift_certificate.code}")
        assert resp.status_code == 200
        data = resp.json()
        assert data["success"] is True
        assert data["certificate"]["code"] == gift_certificate.code
        assert data["certificate"]["valid"] is True
        assert data["certificate"]["remaining_value"] == "3000"

    def test_not_found(self, client):
        resp = client.get(f"{self.url}?code=INVALID-CODE")
        assert resp.status_code == 404
        assert resp.json()["success"] is False

    def test_empty_code(self, client):
        resp = client.get(self.url)
        assert resp.status_code == 400


# ── Страница ────────────────────────────────────────────────────────────────


@pytest.mark.django_db
class TestCertificatesPage:
    def test_status_200(self, client):
        resp = client.get("/certificates/")
        assert resp.status_code == 200

    def test_template(self, client):
        resp = client.get("/certificates/")
        assert "website/certificates.html" in [t.name for t in resp.templates]
