# Generated by Django 5.2.5 on 2026-02-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('analytics', 'Аналитика'), ('offers', 'Акции')], max_length=20, verbose_name='Тип агента')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('done', 'Готово'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('triggered_by', models.CharField(default='scheduler', max_length=50, verbose_name='Запущен')),
                ('input_context', models.JSONField(blank=True, default=dict, verbose_name='Входной контекст')),
                ('raw_response', models.TextField(blank=True, verbose_name='Ответ LLM')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
            ],
            options={
                'verbose_name': 'Задача агента',
                'verbose_name_plural': 'Задачи агентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Всего заявок')),
                ('processed', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('unprocessed', models.PositiveIntegerField(default=0, verbose_name='Не обработано')),
                ('top_services', models.JSONField(blank=True, default=list, verbose_name='Топ услуг')),
                ('masters_load', models.JSONField(blank=True, default=dict, verbose_name='Загрузка мастеров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Метрика дня',
                'verbose_name_plural': 'Метрики по дням',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AgentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Резюме')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='agents.agenttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Отчёт агента',
                'verbose_name_plural': 'Отчёты агентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
