# Generated by Django 5.2.5 on 2026-02-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='agent_type',
            field=models.CharField(choices=[('analytics', 'Аналитика'), ('offers', 'Акции'), ('offer_packages', 'Пакеты предложений'), ('smm_growth', 'SMM-контент'), ('seo_landing', 'SEO-аудит лендингов'), ('analytics_budget', 'Бюджет и воронка')], max_length=20, verbose_name='Тип агента'),
        ),
        migrations.CreateModel(
            name='ContentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('platform', models.CharField(choices=[('vk', 'ВКонтакте'), ('instagram', 'Instagram'), ('telegram', 'Telegram')], max_length=20, verbose_name='Платформа')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('post_type', models.CharField(choices=[('post', 'Пост'), ('story', 'Stories'), ('reel', 'Reels/Клип')], max_length=20, verbose_name='Тип публикации')),
                ('theme', models.CharField(max_length=300, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Описание контента')),
                ('hashtags', models.TextField(blank=True, verbose_name='Хэштеги')),
                ('cta', models.CharField(blank=True, max_length=200, verbose_name='Призыв к действию')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_plans', to='agents.agenttask', verbose_name='Задача агента')),
            ],
            options={
                'verbose_name': 'Контент-план',
                'verbose_name_plural': 'Контент-планы',
                'ordering': ['week_start', 'day_of_week', 'platform'],
                'indexes': [models.Index(fields=['week_start', 'platform'], name='agents_cp_week_platform_idx'), models.Index(fields=['is_published'], name='agents_cp_is_published_idx')],
            },
        ),
    ]
