# Generated by Django 5.2.5 on 2026-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_contentplan_new_agent_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoKeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кластера')),
                ('service_slug', models.CharField(blank=True, help_text='Slug из модели Service для автосвязи с данными Вебмастера', max_length=200, verbose_name='Slug услуги')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Список запросов, например: ["антицеллюлитный массаж", "массаж пенза"]', verbose_name='Ключевые запросы')),
                ('target_url', models.CharField(help_text='Канонический URL страницы, например: /uslugi/antitsellyulitny-massazh/', max_length=500, verbose_name='Целевой URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'SEO-кластер запросов',
                'verbose_name_plural': 'SEO-кластеры запросов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeoRankSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Начало недели (пн)')),
                ('page_url', models.CharField(blank=True, help_text='Относительный URL, например /uslugi/massazh/', max_length=500, verbose_name='URL страницы')),
                ('query', models.CharField(blank=True, help_text='Текст запроса из Яндекс.Вебмастера или пусто для page-уровня', max_length=300, verbose_name='Поисковый запрос')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('ctr', models.FloatField(default=0.0, verbose_name='CTR (0–1)')),
                ('avg_position', models.FloatField(default=0.0, verbose_name='Средняя позиция')),
                ('source', models.CharField(default='webmaster', max_length=50, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'SEO-снимок позиций',
                'verbose_name_plural': 'SEO-снимки позиций',
                'ordering': ['-week_start', '-clicks'],
                'indexes': [models.Index(fields=['week_start', 'page_url'], name='agents_seo_week_page_idx'), models.Index(fields=['week_start', 'query'], name='agents_seo_week_query_idx')],
                'unique_together': {('week_start', 'page_url', 'query')},
            },
        ),
    ]
