# Generated by Django 5.2.5 on 2026-02-25 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_seokeywordcluster_seoranksnapshot'),
        ('services_app', '0033_service_emoji_service_related_services_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('create_landing', 'Создать страницу'), ('update_meta', 'Обновить мета-теги'), ('add_faq', 'Добавить FAQ'), ('fix_technical', 'Технический баг'), ('rewrite_cta', 'Переписать CTA'), ('add_content_block', 'Добавить блок')], max_length=30, verbose_name='Тип задачи')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('done', 'Готово')], default='open', max_length=20, verbose_name='Статус')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('target_url', models.CharField(blank=True, max_length=500, verbose_name='Целевой URL')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'SEO задача',
                'verbose_name_plural': 'SEO задачи',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='seokeywordcluster',
            name='geo',
            field=models.CharField(default='Пенза', max_length=100, verbose_name='Гео'),
        ),
        migrations.AddField(
            model_name='seokeywordcluster',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_clusters', to='services_app.servicecategory', verbose_name='Категория услуги'),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На модерации'), ('published', 'Опубликована'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('meta_title', models.CharField(max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.CharField(max_length=160, verbose_name='Meta Description')),
                ('h1', models.CharField(max_length=200, verbose_name='H1')),
                ('blocks', models.JSONField(default=dict, help_text='Структура: {intro, how_it_works, who_is_it_for, contraindications, results, faq:[{question,answer}], cta_text, internal_links}', verbose_name='Блоки контента')),
                ('generated_by_agent', models.BooleanField(default=True, verbose_name='Сгенерировано агентом')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_pages', to='agents.seokeywordcluster', verbose_name='SEO кластер')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_landings', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Посадочная страница',
                'verbose_name_plural': 'Посадочные страницы',
                'ordering': ['-created_at'],
            },
        ),
    ]
