# Generated by Django 5.2.5 on 2026-02-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_seo_add_geo_category_landingpage_seotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoClusterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата снимка')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Суммарные клики')),
                ('total_impressions', models.PositiveIntegerField(default=0, verbose_name='Суммарные показы')),
                ('avg_ctr', models.FloatField(default=0.0, verbose_name='Средний CTR (0-1)')),
                ('avg_position', models.FloatField(default=0.0, verbose_name='Средняя позиция')),
                ('matched_queries', models.PositiveIntegerField(default=0, help_text='Сколько ключей из кластера нашлось в данных Вебмастера', verbose_name='Совпавших запросов')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='agents.seokeywordcluster', verbose_name='Кластер')),
            ],
            options={
                'verbose_name': 'Снимок кластера',
                'verbose_name_plural': 'Снимки кластеров',
                'ordering': ['-date', 'cluster'],
                'indexes': [models.Index(fields=['date', 'cluster'], name='agents_cls_date_cluster_idx')],
                'unique_together': {('cluster', 'date')},
            },
        ),
    ]
