# Generated by Django 5.2.5 on 2026-02-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_seoclustersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='source_markdown',
            field=models.TextField(blank=True, help_text='Маркдаун-бриф, переданный при генерации. Хранится для аудита.', verbose_name='Исходный маркдаун'),
        ),
    ]
