# Generated by Django 5.2.5 on 2026-02-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_landingpage_add_source_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='blocks',
            field=models.JSONField(blank=True, default=dict, help_text='Структура: {intro, how_it_works, who_is_it_for, contraindications, results, faq:[{question,answer}], cta_text, internal_links}', verbose_name='Блоки контента'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='h1',
            field=models.CharField(blank=True, max_length=200, verbose_name='H1'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
    ]
