# Generated by Django 5.2.13 on 2026-04-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_alter_landingpage_blocks_alter_landingpage_h1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttask",
            name="agent_type",
            field=models.CharField(
                choices=[
                    ("analytics", "Аналитика"),
                    ("offers", "Акции"),
                    ("offer_packages", "Пакеты предложений"),
                    ("smm_growth", "SMM-контент"),
                    ("seo_landing", "SEO-аудит лендингов"),
                    ("analytics_budget", "Бюджет и воронка"),
                    ("trend_scout", "Разведка трендов"),
                ],
                max_length=20,
                verbose_name="Тип агента",
            ),
        ),
        migrations.CreateModel(
            name="TrendSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("yandex_suggest", "Яндекс подсказки"),
                            ("vk_social", "VK группы"),
                        ],
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата сбора")),
                ("raw_data", models.JSONField(verbose_name="Сырые данные")),
                ("summary", models.TextField(blank=True, verbose_name="Анализ GPT")),
                (
                    "trends",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Выделенные тренды"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
            ],
            options={
                "verbose_name": "Снимок трендов",
                "verbose_name_plural": "Снимки трендов",
                "ordering": ["-date"],
                "unique_together": {("source", "date")},
            },
        ),
    ]
