# Generated by Django 5.2.5 on 2026-03-04 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_landingpage_blocks_alter_landingpage_h1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текстовый блок'), ('accent', 'Акцентный блок (цветной фон)'), ('checklist', 'Чеклист (✅ пункты)'), ('identification', 'Блок идентификации (Узнаёте себя?)'), ('cta', 'CTA-кнопка (Записаться)'), ('price_table', 'Таблица цен'), ('accordion', 'Аккордеон (раскрывающийся блок)'), ('faq', 'FAQ — вопросы и ответы'), ('special_formats', 'Особые форматы'), ('subscriptions', 'Абонементы / экономия'), ('navigation', 'Навигация (Не знаете, что выбрать?)'), ('html', 'Произвольный HTML')], max_length=30, verbose_name='Тип блока')),
                ('title', models.CharField(blank=True, help_text='Заголовок (H2 или H3). Можно оставить пустым.', max_length=200, verbose_name='Заголовок блока')),
                ('heading_level', models.CharField(choices=[('h2', 'H2 — заголовок блока'), ('h3', 'H3 — подзаголовок')], default='h2', help_text='H2 — основной заголовок блока. H3 — подзаголовок внутри блока.', max_length=2, verbose_name='Уровень заголовка')),
                ('content', models.TextField(blank=True, help_text='HTML разрешён. Для чеклиста/идентификации — каждый пункт с новой строки. Для FAQ — формат: Вопрос?\\nОтвет текст.\\n---\\nВопрос?\\nОтвет текст.', verbose_name='Содержимое')),
                ('bg_color', models.CharField(blank=True, help_text='Для акцентного/навигационного блока. Пример: #9BAE9E', max_length=20, verbose_name='Цвет фона')),
                ('text_color', models.CharField(blank=True, help_text='Пример: #fff или #333333', max_length=20, verbose_name='Цвет текста')),
                ('btn_text', models.CharField(blank=True, help_text='Для CTA-блока. По умолчанию: Записаться онлайн', max_length=100, verbose_name='Текст кнопки')),
                ('btn_sub', models.CharField(blank=True, help_text='Мелкий текст под кнопкой.', max_length=200, verbose_name='Подпись под кнопкой')),
                ('css_class', models.CharField(blank=True, help_text='Дополнительный класс для стилизации блока.', max_length=100, verbose_name='CSS-класс')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_blocks', to='agents.landingpage', verbose_name='Посадочная страница')),
            ],
            options={
                'verbose_name': 'Блок посадочной страницы',
                'verbose_name_plural': 'Блоки посадочных страниц',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['landing_page', 'is_active', 'order'], name='agents_land_landing_1addb9_idx')],
            },
        ),
    ]
