# Generated by Django 5.2.5 on 2026-04-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentrecommendationoutcome_weeklybacklog_dailymetric_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrecommendationoutcome',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='agents.agentreport', verbose_name='Отчёт'),
        ),
    ]
