# Generated by Django 5.2.5 on 2026-04-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agentrecommendationoutcome_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата снимка')),
                ('period_days', models.IntegerField(default=180, verbose_name='Период анализа (дней)')),
                ('total_clients', models.IntegerField(default=0, verbose_name='Всего клиентов')),
                ('new_clients', models.IntegerField(default=0, verbose_name='Новых клиентов')),
                ('returning_clients', models.IntegerField(default=0, verbose_name='Повторных клиентов')),
                ('retention_30d', models.FloatField(default=0.0, verbose_name='Удержание 30д (%)')),
                ('retention_60d', models.FloatField(default=0.0, verbose_name='Удержание 60д (%)')),
                ('retention_90d', models.FloatField(default=0.0, verbose_name='Удержание 90д (%)')),
                ('avg_frequency', models.FloatField(default=0.0, verbose_name='Средняя частота (визитов/мес на клиента)')),
                ('avg_check', models.FloatField(default=0.0, verbose_name='Средний чек (руб)')),
                ('avg_ltv_180d', models.FloatField(default=0.0, verbose_name='Средний LTV 180д (руб)')),
                ('churn_count', models.IntegerField(default=0, verbose_name='Ушедших клиентов (90д+)')),
                ('churn_rate', models.FloatField(default=0.0, verbose_name='Процент оттока (%)')),
                ('top_churned_services', models.JSONField(blank=True, default=list, verbose_name='Услуги с макс. оттоком')),
                ('cohort_data', models.JSONField(blank=True, default=dict, help_text='Месячные когорты: {"2026-01": {"m0": 100, "m1": 45, ...}}', verbose_name='Когортная матрица')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Снимок удержания',
                'verbose_name_plural': 'Снимки удержания',
                'ordering': ['-date'],
            },
        ),
    ]
