# Generated by Django 5.2.5 on 2026-04-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_alter_agentrecommendationoutcome_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrecommendationoutcome',
            name='agent_type',
            field=models.CharField(choices=[('analytics', 'Аналитика'), ('offers', 'Акции'), ('offer_packages', 'Пакеты предложений'), ('smm_growth', 'SMM-контент'), ('seo_landing', 'SEO-аудит лендингов'), ('analytics_budget', 'Бюджет и воронка'), ('trend_scout', 'Разведка трендов'), ('seo_growth', 'SEO & Growth'), ('landing_qc', 'QC лендингов')], max_length=20, verbose_name='Тип агента'),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='agent_type',
            field=models.CharField(choices=[('analytics', 'Аналитика'), ('offers', 'Акции'), ('offer_packages', 'Пакеты предложений'), ('smm_growth', 'SMM-контент'), ('seo_landing', 'SEO-аудит лендингов'), ('analytics_budget', 'Бюджет и воронка'), ('trend_scout', 'Разведка трендов'), ('seo_growth', 'SEO & Growth'), ('landing_qc', 'QC лендингов')], max_length=20, verbose_name='Тип агента'),
        ),
    ]
