# Generated by Django 5.2.5 on 2026-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_alter_agentrecommendationoutcome_agent_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoranksnapshot',
            name='week_start',
            field=models.DateField(verbose_name='Дата снимка'),
        ),
    ]
